services:
  - docker:dind

stages:
  - build
  - docker

build:
  image: java:8-jdk
  stage: build
  script:
    - ./gradlew clean jar

docker:
  image: docker:latest
  stage: docker
  script:
    - export IMAGE_TAG=$(echo -en $CI_COMMIT_REF_NAME | tr -c '[:alnum:]_.-' '-')
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$IMAGE_TAG"

